server:
  port: 8088 #端口
  address:  0.0.0.0 #本地调试时允许连接
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://139.186.170.118:3306/dingdang?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: mycentos7.6
    hikari:
      minimum-idle: 3
      max-lifetime: 1800000
      maximum-pool-size: 5

#  redis:
#    host:
#    port: 6379
#    database: 0
#    password:

mybatis-plus:
  type-aliases-package: com/nian/business/entry #简化别名，用类的名字充当
  mapper-locations: classpath:mapper/*.xml #类路径下

logging:
  config: classpath:log/logback-spring.xml
  #level自行设定